# VSM exam

In [ ]:
import numpy as np
import scipy.linalg as la
import scipy.stats as st
import math as math

### Random vectors

In [5]:
11/6 - 49/36
15/36

0.4166666666666667

### Entropy

In [217]:
e = st.entropy([1, 2, 3, 4, 5, 6], base = 2)
math.log(6, 2)
#print(e)

2.584962500721156

In [6]:
# SDRUŽENÁ ENROPIE
# m = náhodný vektor
# nezáleží na pořadí x, y
def combined_entropy(m, log_base = 2):
    acc = 0
    it = np.nditer(m.T, flags=['multi_index'])
    for x in it:
        # 0 log(0) je nedifinovaný výraz, který stavíme rovný nule
        if(x != 0):
            acc += -x * math.log(x, log_base)    
    return acc 

In [7]:
# PODMÍNĚNÁ ENTROPIE
# m = náhodný vektor
# cond = čím podmiňuji např. H(X|Y) = 'y' jinak H(Y|X) = 'x'
# záleží na pořadí x, y
def cond_entropy(m, cond, log_base = 2):
    # calc marginal
    x_sum = np.sum(m, axis = 1)
    y_sum = np.sum(m, axis = 0)
    
    acc = 0
    it = np.nditer(m.T, flags=['multi_index'])
    for x in it:
        if(cond == 'y'):
            log_value = x / y_sum[0, it.multi_index[0]]
        else:
            log_value = x/ x_sum[it.multi_index[1], 0]
        
        # 0 log(0) je nedifinovaný výraz, který stavíme rovný nule
        if(log_value != 0):
            acc += -x * math.log(log_value, log_base)    
    return acc

In [8]:
# VZÁJEMNÁ INFORMACE I(X;Y) = SUMA_X SUMA_Y p(x,y) log p(x,y)/p(x)*p(y)
# m = náhodný vektor
# nezáleží na pořadí x, y
def mutual_info(m, log_base = 2):
    # calc marginal
    x_sum = np.sum(m, axis = 1)
    y_sum = np.sum(m, axis = 0)
    
    acc = 0
    it = np.nditer(m.T, flags=['multi_index'])
    for x in it:
        log_value = x / (y_sum[0, it.multi_index[0]] * x_sum[it.multi_index[1], 0])
        # 0 log(0) je nedifinovaný výraz, který stavíme rovný nule
        if(log_value != 0):
            acc += x * math.log(log_value, log_base)    
    return acc

In [28]:
# log function
#-1/4 * math.log(1/4 / 1/2, 2) - 
#-1/4 * math.log(1/4 / 1/2, 2) - 
#m = np.matrix([[1/4, 0, 1/4], [1/4, 0, 0], [0, 1/8, 0], [0, 1/8, 0]])
#m = np.matrix([[1/8, 1/16, 1/32, 1/32], [1/16, 1/8, 1/32, 1/32], [1/16, 1/16, 1/16, 1/16], [1/4, 0, 0, 0]])
m = np.matrix([[1/4, 1/4, 1/2, 0]])
cond_entropy(m, 'x')
#combined_entropy(m)
#mutual_info(m)

0.5

In [38]:
m = np.matrix([[1/2, 1/2], [0, 1]])
#cond_entropy(m, 'y')
#combined_entropy(m)
#st.entropy([1/3, 1/2, 1/6], base=2)
-1/3 * math.log(1/3, 2) - 1/2 * math.log(1/2, 2) - 1/6 * math.log(1/6, 2)
5/3
21/8

2.625

### Markov discrete chain

In [2]:
a = 1/5
b = 3/4

In [3]:
# matice přechodu
P = np.matrix([[1-a, a], [b, 1-b]])
print("P =\n", P)

P =
 [[0.8  0.2 ]
 [0.75 0.25]]


In [11]:
# kontrola že součet řádků je 1
print(np.sum(P, axis = 1))

[[1.]
 [1.]]


In [12]:
# dvoukroková matice přechodu
print("P^2 = \n", P**2)
print(np.sum(P**2, axis = 1))

P^2 = 
 [[0.79   0.21  ]
 [0.7875 0.2125]]
[[1.]
 [1.]]


In [16]:
# počáteční rozdělení
p0 = np.matrix([1,0])
p0

matrix([[1, 0]])

In [19]:
# rozdělení v čase n
n = 3
pn = p0 * P**n
pn

matrix([[0.7895, 0.2105]])

In [22]:
(15/19, 4/19)

(0.7894736842105263, 0.21052631578947367)

In [27]:
# stacionární rozdělení
# lze použít místo ručního řešení rovnic
def stac_dist(P):
    W = np.transpose(P-np.eye(P.shape[0]))
    pi = la.null_space(W)
    pi = np.transpose(pi/sum(pi)) # normalization
    return pi 

In [29]:
P = np.matrix([[0.1, 0.2, 0.4, 0.3], [0.1, 0.2, 0.4, 0.3], [0.1, 0.2, 0.4, 0.3], [0.1, 0.2, 0.4, 0.3]])
stac_dist(P)

array([[0.1, 0.2, 0.4, 0.3]])

In [32]:
36 * 0.1 + 22 * 0.2 + 8 * 0.4 - 6 * 0.3

9.399999999999999

### Příklad 10690

In [59]:
# násobím i řádek a j sloupec matice přechodů
P = np.matrix([[0.6, 0.4, 0, 0], [0.06, 0.58, 0.36, 0], [0.006, 0.112, 0.558, 0.324], [0.001, 0.027, 0.243, 0.729]])
Pr = np.matrix([[0.06, 0.58, 0.36, 0]])
Pc = np.matrix([[0, 0.36, 0.558, 0.243]])

#t = np.transpose(P)

#print(P)
result = P * P
result


matrix([[0.384   , 0.472   , 0.144   , 0.      ],
        [0.07296 , 0.40072 , 0.40968 , 0.11664 ],
        [0.013992, 0.138604, 0.430416, 0.416988],
        [0.004407, 0.062959, 0.322461, 0.610173]])

In [60]:
stac_dist(P)

array([[0.03006697, 0.15598727, 0.37072151, 0.44322424]])

### Příklad č. 10691

In [62]:
P = np.matrix([[1/2, 1/4, 1/4], [1/2, 0, 1/2], [1/4, 1/4, 1/2]])
print(stac_dist(P))

[[0.4 0.2 0.4]]
(0.2, 0.4, 0.4)


In [63]:
P = np.matrix([[0.6, 0.3, 0.1], [0.2, 0.7, 0.1], [0.1, 0.3, 0.6]])
stac_dist(P)

array([[0.3, 0.5, 0.2]])

In [64]:
P = np.matrix([[1, 0, 0, 0, 0], [0.6, 0, 0.4, 0, 0], [0, 0.6, 0, 0.4, 0], [0, 0, 0.6, 0, 0.4], [0, 0, 0, 0, 1]])
stac_dist(P)

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [79]:
B = np.matrix([[1,2]])
V = np.matrix([[17/36, 0], [0, 2/3]])
B * V * np.transpose(B)

matrix([[3.13888889]])

### Testování hypotéz

In [63]:
import scipy.stats as st
#x = np.array([])
#st.ttest_1samp(x, mu0, alternative = 'greater')
# prů
mean = 53/10
n = 10
sn = np.sqrt(3.6 / (n-1))
T = (mean - 5) * np.sqrt(n) / sn
print(T)

alpha = 0.05
t_alpha_n1 = st.t.isf(alpha, n-1)
print(T, t_alpha_n1)

1.4999999999999991
1.4999999999999991 1.8331129326536337
